apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-ci-store
  namespace: demo-eso
spec:
  provider:
    vault:
      server: "http://192.168.1.240:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: approle
          roleId: "a4928a7d-b786-38d8-6e50-06f30526ebe6"
          secretRef:
            name: vault-secret-id
            key: secretId
