apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo3-external-secrets
  namespace: demo3
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo3-sync-secret
  data:
    - secretKey: db-password
      remoteRef:
        key: demo3/database
        property: password
