apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: demo3
spec:
  provider:
    vault:
      server: "http://192.168.1.240:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "demo3"
          serviceAccountRef:
            name: demo3-sa
