apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ci-secret
  namespace: demo2
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-ci-store
    kind: SecretStore
  target:
    name: ci-synced-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: ci/deploy-token
        property: password
