apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-es-1
  namespace: demo1
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: demo-ss-1
    kind: SecretStore
  target:
    name: sync-secret-1
  data:
    - secretKey: demo-1-username # 對應產生 secret (sync-secret-1) 的 key
      remoteRef:
        key: demo-secret-1 # 對應 Vault 的 secret 路徑: secret/data/demo-secret-1
        property: username
    - secretKey: demo-1-password
      remoteRef:
        key: demo-secret-1
        property: password

