apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-ci-store
  namespace: demo2
spec:
  provider:
    vault:
      server: "http://192.168.1.240:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: approle
          roleId: "48773cd5-2cbe-da6c-b0a1-1f23031d584b"
          secretRef:
            name: vault-secret-id
            key: secretId
